// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxASXxH0Y76ahizAhj1W-Um_NCv4gFX0k',
    appId: '1:94742620533:web:5b5283e90e874eb4ef8b3c',
    messagingSenderId: '94742620533',
    projectId: 'flutterproject-cabd5',
    authDomain: 'flutterproject-cabd5.firebaseapp.com',
    storageBucket: 'flutterproject-cabd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyBeKagVDYBHrz7t2e2wSsWs9jxsPUD8',
    appId: '1:94742620533:android:891863e66c5a91d8ef8b3c',
    messagingSenderId: '94742620533',
    projectId: 'flutterproject-cabd5',
    storageBucket: 'flutterproject-cabd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3XTR8_BgGE00_vo9MpYhL7Kdj7crVUI',
    appId: '1:94742620533:ios:bde3e62fd8599504ef8b3c',
    messagingSenderId: '94742620533',
    projectId: 'flutterproject-cabd5',
    storageBucket: 'flutterproject-cabd5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK3XTR8_BgGE00_vo9MpYhL7Kdj7crVUI',
    appId: '1:94742620533:ios:bde3e62fd8599504ef8b3c',
    messagingSenderId: '94742620533',
    projectId: 'flutterproject-cabd5',
    storageBucket: 'flutterproject-cabd5.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxASXxH0Y76ahizAhj1W-Um_NCv4gFX0k',
    appId: '1:94742620533:web:5ba39edf56674cf3ef8b3c',
    messagingSenderId: '94742620533',
    projectId: 'flutterproject-cabd5',
    authDomain: 'flutterproject-cabd5.firebaseapp.com',
    storageBucket: 'flutterproject-cabd5.appspot.com',
  );
}
